# Generated by Django 4.0.4 on 2022-05-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intervyu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=30)),
                ('sana', models.DateField(auto_now_add=True)),
                ('sarlavha', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Maqola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=30)),
                ('sana', models.DateField(auto_now_add=True)),
                ('matn', models.TextField()),
                ('rasm', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
