# Generated by Django 4.0.4 on 2022-05-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_intervyu_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maqola',
            name='rasm',
            field=models.FileField(blank=True, upload_to='maqola_rasm'),
        ),
    ]
